spring:
  application:
    name: purchase-manager-service
  main:
    web-application-type: reactive
  rabbitmq:
    host: rabbitmq.social.local
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC

app:
  mongo:
    host: mongodb.social.local
    port: 27017
    dbname: social-network

server:
  port: ${PORT:8082}
  servlet:
    context-path: /api/v1/